apiVersion: v1
kind: Namespace
metadata:
  name: myapp
  labels:
    name: myapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-app
  namespace: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp-app
  template:
    metadata:
      labels:
        app: myapp-app
    spec:
      containers:
        - name: myapp-deployment
          image: myapp:1.1
          imagePullPolicy: IfNotPresent # Required for local image using k3d
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myapp
spec:
  selector:
    app: myapp-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081 # This is the port of the container